# Generated by Django 2.2.7 on 2020-01-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_auto_20200114_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='nombre',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
