# Generated by Django 3.0.2 on 2020-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20200116_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='puerta',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
